'use strict';
const API='https://khjuxuawpnfrtnsgxvaw.supabase.co/rest/v1',KEY='sb_publishable_d1yDwGba4RoZ557lfAIqlA_BznMGiej',DEFAULT_CODE='CASA-8472';
const CATS=['Todo','Fruta y verdura','Carne y pescado','Lácteos y huevos','Panadería','Bebidas','Congelados','Despensa','Limpieza','Higiene','Otros'];
const RULES={'Fruta y verdura':['platano','banana','manzana','pera','naranja','mandarina','limon','uva','fresa','melon','sandia','piña','mango','kiwi','melocoton','ciruela','aguacate','tomate','lechuga','cebolla','ajo','patata','zanahoria','calabacin','berenjena','pimiento','pepino','brocoli','coliflor','espinaca','champiñon','seta','verdura','fruta'],'Carne y pescado':['pollo','pavo','ternera','vacuno','cerdo','lomo','solomillo','chuleta','carne','hamburguesa','salchicha','chorizo','jamon','bacon','pescado','salmon','atun','merluza','bacalao','sardina','gamba','langostino','marisco','calamar','sepia'],'Lácteos y huevos':['leche','yogur','yogurt','queso','mantequilla','nata','kefir','huevo','cuajada'],'Panadería':['pan','baguette','barra','molde','croissant','bolleria','magdalena','bizcocho'],'Bebidas':['agua','refresco','coca cola','cocacola','pepsi','zumo','jugo','cerveza','vino','cava','sidra','isotonica','energetica'],'Congelados':['congelado','helado','pizza congelada','hielo','croqueta congelada'],'Despensa':['arroz','pasta','macarron','espagueti','fideo','harina','azucar','sal','aceite','vinagre','lenteja','garbanzo','judia','alubia','cereal','galleta','chocolate','cacao','cafe','te','conserva','tomate frito','salsa','mayonesa','ketchup','mostaza','pan rallado','frutos secos','miel','mermelada','especia'],'Limpieza':['detergente','lavavajillas','lejia','amoniaco','limpiador','suavizante','quitagrasas','desinfectante','fregasuelos','estropajo','bayeta','bolsa basura','papel cocina'],'Higiene':['champu','shampoo','gel','jabon','desodorante','pasta dientes','dentifrico','cepillo dientes','papel higienico','compresa','tampon','pañal','toallita','crema corporal','afeitar']};
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9ñ ]+/g,' ').replace(/\s+/g,' ').trim();
function infer(name){const n=norm(name);for(const [c,ws] of Object.entries(RULES))if(ws.some(w=>n.includes(norm(w))))return c;return 'Otros'}
function logo(file){const b=self.LOGOS&&self.LOGOS[file];return b?'data:image/webp;base64,'+b:''}
const LOGOS={'Carrefour':()=>logo('carrefour.webp'),'Lidl':()=>logo('lidl.png'),'Ahorramas':()=>logo('ahorramas.webp'),'Alcampo':()=>logo('alcampo.webp'),'Mercadona':()=>logo('mercadona.png'),'Dia':()=>logo('dia.png'),'Family Cash':()=>logo('family-cash.webp'),'Aldi':()=>logo('aldi.png')};
let house=null,stores=[],items=[],selected='all',section='Todo',poller=null,last='';
const H={'apikey':KEY,'Authorization':'Bearer '+KEY,'Content-Type':'application/json'};
async function api(path,o={}){const r=await fetch(API+path,{...o,headers:{...H,...(o.headers||{})}});if(!r.ok)throw Error(await r.text());if(r.status===204)return null;const t=await r.text();return t?JSON.parse(t):null}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1700)}
function sync(ok){$('sync').textContent=ok?'✓ Sincronizado':'⚠ Sin conexión';$('sync').classList.toggle('off',!ok)}
function build(){document.getElementById('app').innerHTML=`<div class="app"><section id="home" class="screen active"><h1>Mi Compra</h1><div class="sub">👥 Casa</div><div id="sync" class="sync">✓ Sincronizado</div><div class="title">Mis supermercados</div><div id="grid" class="grid"></div><button id="all" class="all"><span style="font-size:25px">🛍️</span><span><strong>Toda la compra</strong><small id="alln"></small></span><span class="arr">›</span></button></section><section id="store" class="screen"><div class="storehead"><button id="back" class="back">‹</button><img id="slogo" class="storelogo"><div class="storeinfo"><b id="sname"></b><span id="scount" class="sub"></span></div></div><input id="search" class="search" placeholder="Buscar producto o sección…"><div id="chips" class="chips"></div><form id="quick" class="quick"><input id="qprod" placeholder="Añadir producto…"><button>+</button></form><div id="list"></div></section><section id="settings" class="screen"><h1>Ajustes</h1><div class="sub" style="margin-bottom:25px">Sincronización de la lista compartida</div><div class="settings"><h2>Tu código de casa</h2><p class="sub">Usa este mismo código en el otro móvil para compartir exactamente la misma lista.</p><div id="code" class="code">${DEFAULT_CODE}</div><br><button id="copy" class="secondary">Copiar código</button></div><div class="settings"><h2>Vincular este móvil</h2><div class="coderow"><input id="pair" placeholder="CASA-8472"><button id="pairb" class="primary">Vincular</button></div><div id="pstatus" class="status"></div></div><div class="settings"><h2>Sincronización</h2><button id="syncnow" class="secondary">Sincronizar ahora</button></div></section></div><button id="fab" class="fab">+</button><nav class="nav"><button id="nh" class="active"><div class="ico">⌂</div>Inicio</button><button id="nb"><div class="ico">🛒</div>Compra</button><button id="ns"><div class="ico">⚙︎</div>Ajustes</button></nav><div id="sheetw" class="sheetwrap"><div class="sheet"><div class="handle"></div><h2>Añadir producto</h2><form id="add"><div class="field"><label>Producto</label><input id="aname" required placeholder="Ej. Leche"></div><div class="field"><label>Supermercado (opcional)</label><select id="astore"></select></div><div class="row2"><div class="field"><label>Sección automática</label><div id="acat" class="autocat">Otros</div></div><div class="field"><label>Cantidad</label><input id="aqty" type="number" min="1" value="1"></div></div><div class="actions"><button type="button" id="cancel" class="secondary">Cancelar</button><button class="primary">Añadir</button></div></form></div></div><div id="toast" class="toast"></div>`;bind()}
function show(id){['home','store','settings'].forEach(x=>$(x).classList.toggle('active',x===id));$('nh').classList.toggle('active',id==='home');$('nb').classList.toggle('active',id==='store');$('ns').classList.toggle('active',id==='settings')}
function count(id){const a=items.filter(x=>id==='all'||x.store_id===id);return{p:a.filter(x=>!x.completed).length,b:a.filter(x=>x.completed).length}}
function home(){$('grid').innerHTML=stores.map(s=>{const c=count(s.id),pct=c.p+c.b?Math.round(c.b/(c.p+c.b)*100):0;return `<button class="card" data-store="${s.id}"><img class="logo" src="${LOGOS[s.name]?.()||''}"><div class="name">${esc(s.name)}</div><div class="pending">${c.p} pendientes</div><div class="bar"><span style="width:${pct}%"></span></div><div class="bought">${c.b} comprados</div></button>`}).join('');$('alln').textContent=count('all').p+' pendientes en total'}
function visible(){let a=items.filter(x=>selected==='all'||x.store_id===selected||(!x.store_id&&selected!=='all'));if(section!=='Todo')a=a.filter(x=>(x.category||'Otros')===section);const q=norm($('search').value);if(q)a=a.filter(x=>norm((x.name||'')+' '+(x.category||'')).includes(q));return a}
function store(){const st=stores.find(s=>s.id===selected);$('slogo').style.display=st?'block':'none';if(st){$('slogo').src=LOGOS[st.name]?.()||'';$('sname').textContent=st.name}else $('sname').textContent='Toda la compra';const a=visible(),p=a.filter(x=>!x.completed).length,b=a.filter(x=>x.completed).length;$('scount').textContent=p+' pendientes · '+b+' comprados';$('chips').innerHTML=CATS.map(c=>`<button class="chip ${c===section?'on':''}" data-cat="${c}">${c}</button>`).join('');$('list').innerHTML=a.length?a.map(x=>`<div class="item ${x.completed?'done':''}" data-id="${x.id}"><button class="check"></button><div class="main"><b>${esc(x.name)}</b><small>${esc(x.category||'Otros')}${!x.store_id?' · cualquier supermercado':''}</small></div><div class="qty"><button class="minus">−</button><b>${x.quantity||1}</b><button class="plus">+</button></div><button class="trash">×</button></div>`).join(''):'<div class="empty">No hay productos en esta sección</div>'}
function render(){home();store();fillStores()}
function fillStores(){$('astore').innerHTML='<option value="">Sin supermercado · comprar en cualquiera</option>'+stores.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}
async function load(force=false){if(!house)return;try{const [s,i]=await Promise.all([api('/stores?select=*&household_id=eq.'+house.id+'&order=sort_order.asc'),api('/items?select=*&household_id=eq.'+house.id+'&order=created_at.asc')]),snap=JSON.stringify([s,i]);stores=s||[];items=i||[];if(force||snap!==last){last=snap;render()}sync(true)}catch(e){sync(false)}}
async function resolve(code){const rows=await api('/households?select=*&pairing_code=eq.'+encodeURIComponent((code||DEFAULT_CODE).trim().toUpperCase())+'&limit=1');if(!rows?.[0])throw Error();house=rows[0];const c=house.pairing_code||DEFAULT_CODE;localStorage.setItem('mc3_code',c);$('code').textContent=c;await load(true);clearInterval(poller);poller=setInterval(()=>load(false),3000)}
async function insert(o){await api('/items',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(o)});await load(true)}async function patch(id,o){await api('/items?id=eq.'+id,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(o)});await load(true)}async function del(id){await api('/items?id=eq.'+id,{method:'DELETE',headers:{Prefer:'return=minimal'}});await load(true)}
function openStore(id){selected=id;section='Todo';$('search').value='';show('store');store()}function openSheet(){fillStores();$('aname').value='';$('aqty').value=1;$('astore').value='';if(selected!=='all'&&stores.some(s=>s.id===selected))$('astore').value=selected;$('acat').textContent='Otros';$('sheetw').classList.add('show');setTimeout(()=>$('aname').focus(),60)}
function bind(){$('grid').onclick=e=>{const c=e.target.closest('[data-store]');if(c)openStore(c.dataset.store)};$('all').onclick=()=>openStore('all');$('back').onclick=()=>show('home');$('nh').onclick=()=>show('home');$('nb').onclick=()=>openStore('all');$('ns').onclick=()=>show('settings');$('fab').onclick=openSheet;$('cancel').onclick=()=>$('sheetw').classList.remove('show');$('sheetw').onclick=e=>{if(e.target===$('sheetw'))$('sheetw').classList.remove('show')};$('search').oninput=store;$('chips').onclick=e=>{const b=e.target.closest('[data-cat]');if(b){section=b.dataset.cat;store()}};$('aname').oninput=()=>{$('acat').textContent=infer($('aname').value)};$('quick').onsubmit=async e=>{e.preventDefault();const n=$('qprod').value.trim();if(!n)return;if(selected==='all'){openSheet();$('aname').value=n;$('acat').textContent=infer(n);return}try{await insert({household_id:house.id,store_id:selected,name:n,quantity:1,category:infer(n)});$('qprod').value=''}catch{toast('No se pudo añadir')}};$('add').onsubmit=async e=>{e.preventDefault();const n=$('aname').value.trim(),sid=$('astore').value;if(!n)return;try{await insert({household_id:house.id,store_id:sid||null,name:n,quantity:Math.max(1,+$('aqty').value||1),category:infer(n)});$('sheetw').classList.remove('show');toast(sid?'Producto añadido':'Añadido · cualquier supermercado')}catch{toast('No se pudo añadir')}};$('list').onclick=async e=>{const r=e.target.closest('.item');if(!r)return;const x=items.find(i=>i.id===r.dataset.id);if(!x)return;try{if(e.target.classList.contains('check'))await patch(x.id,{completed:!x.completed});else if(e.target.classList.contains('trash'))await del(x.id);else if(e.target.classList.contains('plus'))await patch(x.id,{quantity:(x.quantity||1)+1});else if(e.target.classList.contains('minus'))await patch(x.id,{quantity:Math.max(1,(x.quantity||1)-1)})}catch{toast('No se pudo guardar')}};$('copy').onclick=async()=>{try{await navigator.clipboard.writeText($('code').textContent);toast('Código copiado')}catch{}};$('pairb').onclick=async()=>{const c=$('pair').value.trim();$('pstatus').textContent='Buscando…';try{await resolve(c);$('pstatus').textContent='✓ Vinculado correctamente'}catch{$('pstatus').textContent='Código no encontrado'}};$('syncnow').onclick=()=>load(true)}
build();resolve(localStorage.getItem('mc3_code')||DEFAULT_CODE).catch(()=>{sync(false);show('settings')});